# Jekyll Specific Stuff
markdown: rdiscount
pygments: true
permalink: /posts/:title
paginate: 5 # the number of post per page
rdiscount:
  extensions: [smart]

# User Options
name: Mikey Wills
baseurl: /bryant
description: "A designer based out of Orange County, CA. Front end developer at Style Hatch. Just killing time between meals."
email: mikey@muke.me
twitter: mukealicious
icon_url: http://muke.me/images/mikeyface.png
disqus_shortname: jekyllbyron

# prose.io template
prose:
  rooturl: '_posts'
  siteurl: 'http://nevvkid.github.io/bryant/'
  relativeLinks: 'http://nevvkid.github.io/bryant/links.jsonp'
  media: '_posts/media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "text"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "category"
        field:
          element: "text"
          label: "Category"
          value: "posts"
      - name: "type"
        field:
          element: "select"
          label: "Type"
          placeholder: "Select a Post Type"
          options:
            - name: "Text"
              value: "text"
            - name: "Photo"
              value: "photo"
            - name: "Embed"
              value: "embed"
            - name: "Quote"
              value: "quote"
            - name: "Link"
              value: "link"
          selected: "text"
      - name: "photo_url"
        field:
          element: "text"
          label: "Photo URL (select Post Type - Photo)"
          value: "http://somesite.com/images/someimage.jpg"
      - name: "camera"
        field:
          element: "text"
          label: "Camera (select Post Type - Photo)"
          value: "Fujifilm Finepix X100"
      - name: "aperture"
        field:
          element: "text"
          label: "Aperture (select Post Type - Photo)"
          value: "f/4"
      - name: "exposure"
        field:
          element: "text"
          label: "Exposure (select Post Type - Photo)"
          value: "1/250th"
      - name: "focal_length"
        field:
          element: "text"
          label: "Focal Length (select Post Type - Photo)"
          value: "23mm"
    _posts/quote:
      - name: "layout"
        field:
          element: "text"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "category"
        field:
          element: "text"
          label: "Category"
          value: "posts"
      - name: "type"
        field:
          element: "text"
          label: "Post Type"
          value: "quote"

# Color Options
text_color: '#444444'
accent_color: '#d95e3f'
hover_color: '#a7543f'
subtle_color: '#999999'
subtle_border: '#e9e9e9'
title_color: '#222222'
text_on_accent_color: '#ffffff'
header_background: '#385975'
header_text_color: '#dfe6ec'
header_accent_color: '#d95e3f'
header_title_color: '#ffffff'
header_subtle_color: '#597790'
header_subtle_border: '#597790'
background: '#fcfcfc'
post_background:

# Footer
footer_title: About Mukey
footer_description: "I am a purpose driven designer with a passion for products. A realigner not a redesigner. I don't like making things pretty, I like making them better."
social_links_title: Picture Me Rollin
github_url: https://github.com/Mukealicious
flickr_url: 
instagram_url: http://instagram.com/mukealicious
vimeo_url: 
facebook_url: 
google_plus_url: https://plus.google.com/111592174684877854482/posts
pinterest_url: 
tumblr_url: 
linkedin_url: 
dribbble_url: http://dribbble.com/mukealicious
lastfm_url: 
rdio_url: http://www.rdio.com/people/Mukealicious/
spotify_url: 
skype_url: 
soundcloud_url: 
behance_url: 